### ISSUE TITLE
Is there really a benefit to using a worker?

### ISSUE THREAD

**Issue by stefansundin** [gruhn/barcode-detector#4]
Hello,

I have recently made my own quazi-polyfill for BarcodeDetector. You can find it here: https://github.com/stefansundin/qr-detector.js. It only aims to implement the QR format.

While working on it and researching other packages, I started wondering why most other packages implemented their detection using web workers. In my limited testing I have not really seen a noticeable benefit when using web workers. I am wondering if there's a solid test that I can run to see the benefits? I would be very thankful for learning in what cases it makes a difference.

Furthermore, I think the fact that web workers are utilized should be very explicitly stated in this project's README. To be honest I think a polyfill shouldn't really add workers into the mix, because that's not something that BarcodeDetector requires you to use. I don't even think it is desirable since in my opinion it goes beyond the responsibilities of a polyfill.

Thanks for your time!

**Comment by gruhn** [comment]
The usual argument is: everything outside the web worker is running on the UI thread. If you do a lot of computation on the UI thread it blocks rendering and the website gets sluggish. If there’s a memory leak it won’t just kill the web worker but crash the whole website.

I don’t have any empirical evidence for that. I basically just accept this argument. But its certainly a pain to deal with the web worker. 

On the subject of scope: Native BarcodeDetector implementations don’t run on the UI thread. That’s why you have to `await` after a `detect` call. In that sense I think using a web worker in a polyfill is closer to the native implementation. That can be discussed but I don’t agree that polyfills shouldn’t use web workers *in general*. Would you also say polyfills should never use the fetch API?

**Comment by stefansundin** [comment]
That makes a lot of sense. Thanks for the reply.
